language: node_js

node_js:
  - 8

env:
  global:
    - NODE_ENV=test

cache:
  yarn: true

before_install:
  - npm install -g yarn

before_script:
  - export PATH=$PATH:./node_modules/.bin
  - |
    npm run build
    npm run serve > ./run.log 2>&1 &

script:
  # - npm run lint
  - npm run test
